version: "3"
services:
  v2ray:
    image: v2ray/official
    container_name: v2ray
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json
      - ./v2ray/log:/var/log/v2ray
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    expose:
      - "10086"
  caddy:
    image: caddy:latest
    container_name: v2ray_caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./log:/var/log/caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ACME_AGREE=true
    links:
      - "v2ray"
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
